export const canciones = [
  "Tacomendaciones/A Tapdancer's Dilema.mp3",
  "Tacomendaciones/Across The Universe.mp3",
  "Tacomendaciones/Agust D - People Pt.2.mp3",
  "Tacomendaciones/All You Need Is Love.mp3",
  "Tacomendaciones/August's Rhapsody.mp3",
  "Tacomendaciones/Beethoven quartet no. 15 in A minor, op. 132, 3rd mov. (Molto adagio).mp3",
  "Tacomendaciones/Blackbird.mp3",
  "Tacomendaciones/Bob Dylan - Blowin' in the Wind.mp3",
  "Tacomendaciones/Bossa Love Songs - Can't Help Falling In Love.mp3",
'Tacomendaciones/Bright Eyes-First Day of My Life.mp3',
'Tacomendaciones/Canserbero - Únetenos.mp3',
'Tacomendaciones/Canserbero - Vida.mp3',
'Tacomendaciones/Christopher Tin - Baba Yetu.mp3',
'Tacomendaciones/Christopher Tin - Sogno di Volare.mp3',
'Tacomendaciones/cinnamons evening cinema - summertime.mp3',
'Tacomendaciones/Coeur de Pirate - Comme des enfants.mp3',
'Tacomendaciones/Cœur de pirate - Corbeau.mp3',
'Tacomendaciones/Cœur de pirate - Fondu au noir [Version officielle
  ] [uMqLr0hhSwM
  ].mp3',
'Tacomendaciones/Colour Me In.mp3',
'Tacomendaciones/Cry for the Moon.mp3',
'Tacomendaciones/Cuando Nada Me Quede.mp3',
'TacomnedacionesDonde Descansa La Esperanza.mp3',
'Tacomendaciones/Dos Mundos.mp3',
'Tacomendaciones/El Gato Lopez.mp3',
'Tacomendaciones/El Gran Varón.mp3',
'Tacomendaciones/Eminem - Darkness.mp3',
'Tacomendaciones/Eminem - Guts Over Fear ft. Sia.mp3',
'Tacomendaciones/Flower Face - Bedhead.mp3',
'Tacomendaciones/Flower Face - Cornflower Blue.mp3',
'Tacomendaciones/Gaia.mp3',
'Tacomendaciones/George Harrison-Give Me Love.mp3',
'Tacomenaciones/Given Up.mp3',
'./Good Charlotte - I Just Wanna Live.mp3',
'./i love you more than you will ever know.mp3',
'./Is There Still Anything That Love Can Do.mp3',
'./Jane Doe.mp3',
'./Jason Mraz - I Won't Give Up.mp3',
'./Je veux.mp3',
'./Jeff Buckley - Hallelujah.mp3',
'./Jónsi - Boy Lilikoi.mp3',
'./Jónsi - Go Do.mp3',
'./Kickapoo.mp3',
'./La Costa del Silencio-Mägo de Oz.mp3',
'./La gusana ciega - Tornasol.mp3',
'./Ladrando a la luna.mp3',
'./Last Nite - The Strokes.mp3',
'./Life Goes On - August D.mp3',
'./Life Goes On - BTS.mp3',
'./Life Is Wonderful.mp3',
'./Like a scent.mp3',
'./Like Toy Soldiers.mp3',
'./Lo Estoy Intentando.mp3',
'./Louis Armstrong - La Vie En Rose.mp3',
'./Louis Armstrong What A Wonderful World.mp3',
'./Lucha De Gigantes.mp3',
'./Lytos - Léelo del Revés.mp3',
'./MAGO DE OZ  (CREO).mp3',
'./Mägo de Oz - Hoy toca ser feliz.mp3',
'./Mago de oz - La Rosa de los Vientos.mp3',
'./Man in the Mirror.mp3',
'./MC-solaar - la vie est belle.mp3',
'./Mestizaje [CTM9vZSVZfc
  ].mp3',
'./Mikrocosmos.mp3',
'./Mr. Curiosity.mp3',
'./My Chemical Romance - SING.mp3',
'./Nach - Gratis.mp3',
'./NACH, QUIERO CONTARTE.mp3',
'./Nanna - Disaster Master.mp3',
'./Nanna - Godzilla.mp3',
'./Nanna - Igloo.mp3',
'./Nanna - Milk.mp3',
'./Never Shout Never - first dance.mp3',
'./New Radicals - You Get What You Give.mp3',
'./Ob-La-Di, Ob-La-Da.mp3',
'./Of Monsters And Men - Love Love Love.mp3',
'./One Love Bob Marley.mp3',
  "./One Ok Rock - Notes'n'Words.mp3",
'./Porter Robinson ft. Amy Millan - Divinity.mp3',
'./Qué Puedo Decir.mp3',
'./Queen - Dont Stop Me Now.mp3',
'./Queen - Love Of My Life.mp3',
'./RADWIMPS - Kaiko.mp3',
'./RADWIMPS - MAKAFUKA.mp3',
'./RADWIMPS Kanata Haruka.mp3',
'./RADWIMPS Utakata uta.mp3',
'./Rusted Rood - Send me on my way.mp3',
'./Scene Eight The Spirit Carries On.mp3',
'./Sie7e - Tengo tu love.mp3',
'./Sigur Rós - Ára Bátur.mp3',
'./Sigur Ros - Glósóli.mp3',
'./Sigur Ros - Hoppipolla.mp3',
'./Solaar Pleure.mp3',
  "./Stayin' Alive.mp3",
'./Sticks & Stones.mp3',
'./Stir It Up.mp3',
'./The Final Countdown.mp3',
'./The Long And Winding Road.mp3',
'./This Is Home.mp3',
'./Tipling Rock - Love Without a Reason.mp3',
'./To the sky.mp3',
'./Toploader - Dancing in the Moonlight.mp3',
'./Trusty and True.mp3',
'./un palido punto azul - Carl Sagan.mp3',
'./Untitled #3 - sigur ros.mp3',
'./Untitled #4 (Njósnavélin).mp3',
'./Ven a mi Inuyasha.mp3',
'./Will You Be There.mp3',
'./Zaz - Port Coton.mp3',
];
